"""Render credit memo to Markdown format."""
from creditmemo import fields
from creditmemo.data.schema import DealProfile
from creditmemo.sections import (
    executive, borrower, transaction,
    financial, impact, risk, recommendation
)

#: The memo's sections, in document order. One module per ``## `` heading.
#:
#: F16. Declared as data because :meth:`creditmemo.memo.CreditMemo.section_count`
#: needs the *structure* of the memo and used to reach for its text instead,
#: counting occurrences of ``"\n## "`` in the rendered Markdown. A caller who
#: wrote a ``## `` line into any prose field — ``deal_summary``, a mission, an
#: impact narrative, all of which the memo reproduces verbatim by design —
#: inflated the count: a seven-section memo reported eight. The renderer now
#: iterates this tuple and the count is its length, so the two cannot disagree
#: and neither can be moved by an input.
SECTIONS = (
    executive, borrower, transaction,
    financial, impact, risk, recommendation,
)

#: What the footer line says before the version. Held as a constant so the
#: gates and the README can name the same string.
VERSION_FOOTER_PREFIX = "Generated by credit-memo "


def version_footer() -> str:
    """
    The one line in the memo that identifies the release that produced it.

    **Neither rendering carried a version stamp through 0.2.1.** Measured on
    the published wheel: none of ``0.2.1``, ``credit-memo``, ``creditmemo``,
    ``Generated`` or ``version`` appeared in the Markdown or in the ``.docx``,
    in any case. A user with a folder of memos could not tell which release
    produced any of them — and the README's own remediation instruction, twice
    and in bold, is *"If you generated Word memos with either release,
    regenerate them"* and *"the small figures in them are wrong — regenerate
    them"*. That instruction could not be carried out against the artifacts the
    package produces, because nothing in an artifact said which release it was.

    ``__version__`` is read at call time, from the installed package, not
    baked in as a literal: a literal is how the next release ships a memo that
    lies about itself. The import is deferred because ``creditmemo/__init__.py``
    imports this module, so a module-level import would be circular — and
    deferring it is also what lets
    ``test_g16_the_footer_follows_the_installed_version`` set a different
    ``__version__`` and watch the footer follow it, which a literal cannot do.
    """
    from creditmemo import __version__
    return f"{VERSION_FOOTER_PREFIX}{__version__}"


def render(deal: DealProfile) -> str:
    """
    Render a complete credit memo as a Markdown string.

    Args:
        deal: DealProfile with all deal inputs

    Returns:
        Full credit memo as Markdown string
    """
    parts = [
        f"# Investment Committee Memorandum",
        f"# {deal.deal_name}",
        f"",
        f"**Fund:** {fields.or_placeholder(deal.fund_name, 'N/A')}",
        f"**Prepared By:** {deal.prepared_by}",
        f"**Date:** {deal.prepared_date}",
        f"**IC Date:** {fields.or_placeholder(deal.ic_date, 'TBD')}",
        f"",
    ]
    for section in SECTIONS:
        parts += ["---", "", section.generate(deal)]

    # The version stamp closes the memo. It goes here rather than in the .docx
    # renderer because that renderer is a pure function of this Markdown, so
    # one line gives both formats the same stamp and neither can drift.
    parts += ["---", "", version_footer(), ""]

    return "\n".join(parts)


def save(deal: DealProfile, path: str) -> None:
    """Save credit memo to a Markdown file."""
    content = render(deal)
    with open(path, "w") as f:
        f.write(content)
    print(f"Credit memo saved to {path}")
